package-lock.json, src/services/api.js
=> [Grupo 4] Requisito 1

package-lock.json, src/services/api.js
=> [Grupo18]-project-frontend-online-store

src/services/api.js
=> [Grupo 4] Adiciona nomes dos participantes

src/services/api.js
---
- criadas as consts globais para representar os endpoints da api;
- criação da função getCategries();
- criação da função getPRoductsFromCategryAndQuery;
=> [Requisito 1][Grupo 1] Criacao das duas funcoes da api.js

src/App.js, src/components/EmptyCart.js, src/pages/Home.js, src/pages/ShoppingCart.js
3. Crie a página do carrinho de compras
PRIORIDADE 1 - Criar o botão de carrinho de compras na tela principal, de listagem de produtos, e criar uma tela para o carrinho de compras, inicialmente vazio.
Tela do carrinho de compras
Tela principal - Com botão do carrinho de compras
Observações técnicas
Quem usa o site irá adicionar produtos em seu carrinho de compras e finalizar a compra. A listagem de produtos deve ter um ícone de carrinho que, ao ser clicado, leva à página do carrinho. Inicialmente, o carrinho deverá estar vazio.
O elemento com o ícone de carrinho de compras deve ficar visível na página inicial (listagem de produtos) e também na página de detalhes de um produto (descrita posteriormente)
Adicione o atributo data-testid com o valor shopping-cart-button no elemento com o ícone …
=> [Grupo 12] Requisito 3: Criada a pagina do carrinho de compras

package-lock.json, package.json, src/App.js, src/pages/Main.js
=> [ Requisito 2 ] [ Grupo 1 ] Campo busca tela principal

src/App.js, src/services/api.js
Cria função de requisição a API
=> adiciona requisito 1

src/App.js, src/pages/Home.jsx
Obs: o nome da branch deveria ser 'main-group-7-req2'
=> Requisito 2

package-lock.json, src/App.js, src/components/InputSearch/InputSearch.js, src/services/api.js
Os requisitos 1 e 2 foram feitos com todos presentes.
Foi renderizado um input de busca.
=> [Grupo 15] Requisito 2 - Input de Busca

package-lock.json, src/App.js, src/services/api.js
Abertura do módulo da api do ML pegando categorias e pegando produtos através do $CATEGORY_ID e $QUERY.
O requisito 1 foi feito e revisado por todos os presentes do grupo no Slack.
=> [Grupo 15] Requisito 01 - API do ML

package-lock.json, src/App.js, src/services/api.js
tentando reparar o merge para base main-group-9
=> Main group 9 requisito1

src/App.css, src/components/Categories.js, src/pages/Home.js
PRIORIDADE 1 - Listar filtros de categoria obtidos da API na tela principal, de listagem do produto. A requisição da API para recuperar as categorias deve ser feita uma única vez após o carregamento da tela.
Tela principal - Com a lista de categorias
Observações técnicas
Um endpoint da API do Mercado Livre retorna as categorias de produto disponíveis para busca. Em momento posterior tais categorias serão usadas para filtrar a listagem de produtos. Por hora, elas devem ser listadas na tela da listagem, conforme protótipo.
Adicione o atributo data-testid com o valor category nos elementos que possuem os nomes das categorias
O que será verificado:
- Exibe as categorias retornadas pela API na página de listagem de produtos
=> [Grupo 12] requisito 4: Liste as categorias de produtos disponíveis via API na página principal

package-lock.json, package.json, src/components/SearchBar.jsx, src/pages/Home.jsx, src/pages/ShoppingCart.jsx, src/services/api.js
G10 - Requisitos 1, 2 e 3 finalizados e com correção dos conflitos
=> G10 - Requisitos 1, 2 e 3

src/Components/SearchBar.jsx
Adiciona requisito 5 resolvido
=> [Grupo 24] 

src/components/Category.js, src/pages/Main.js
=> [ Requisito 4 ][ Grupo 1 ] Liste as categorias de produtos disponíveis via API na página principal.

src/components/CategoriesList.jsx, src/pages/Home.jsx
Cria a pasta "components" e o componente CategoriesList.
Adiciona esse componente na página Home.
=> Requisito 4

src/App.js, src/components/InputSearch/InputSearch.js, src/pages/Home.js, src/pages/ShoppingCart.js
Criada rotas para o carrinho de compras (inicialmente vazio) e para o input de busca (considerada a Home)
=> [Grupo 15] Requisito 3 - Rotas pro Cart e Home

src/App.js, src/components/ButtonAddCart.jsx, src/pages/Cart.jsx, src/pages/Home.jsx, src/pages/ProductDetail.jsx
Criar o botão de carrinho de compras na tela principal, de listagem de produtos, e criar uma tela para o carrinho de compras, inicialmente vazio.
=> [GRUPO 7] Requisito 3

src/App.js, src/components/CategoriesList.js, src/components/Category.js, src/components/ListProducts.js, src/pages/Home.js
Added display of categories returned by API on product listing page.
=> Adding requirement 4

package-lock.json, src/App.css, src/components/Card.js, src/components/CardsList.js, src/components/EmptyList.js, src/pages/Home.js, src/services/api.js
PRIORIDADE 1 - Criar a listagem de produtos. Fazer a exibição resumida do produto (o "card" que aparece na listagem). A exibição deve ter título, foto e preço. Fazer requisição à API do Mercado Livre enviando os termos buscados por quem usa e usar o retorno para fazer a listagem dos produtos. Se a busca não retornar resultados, gerar a tela correspondente com o texto "Nenhum produto foi encontrado".
Tela principal - Após a busca
Tela principal - Nenhum produto encontrado
Observações técnicas
A alma do site é a sua lógica de busca e listagem de produtos. Após digitar seus termos na caixa de busca uma requisição deverá ser feita à API do Mercado Livre utilizando a ação de um botão, tendo como parâmetros a frase digitada, e tais produtos deverão aparecer na tela numa exibição resumida, …
=> [Grupo 12] Requisito 05: Liste os produtos buscados por termos, com os dados resumidos, associados a esses termos

src/pages/Home.js
=> [ Requisito 4 e 6 ][ Grupo 1] Toggle products categories

src/pages/Home.js
=> [ Requisito 5 ][ Grupo 1 ] Product search logic

src/components/MainPage.css, src/components/MainPage.js
=> [Grupo-18]- estilizaçao da pagina principal

src/components/Categories.js, src/pages/Home.js
**PRIORIDADE 2**  - Como pessoa usuária, eu quero clicar em uma categoria e ver a listagem de produtos ser filtrada de acordo com os produtos daquela categoria.
O que será verificado:
-   A página, agora, deve poder usar as categorias recuperadas da API para filtrar os produtos buscados. Os termos e as categorias inseridas por quem usa devem ser usados em conjunto para filtragens mais específicas.
O que será verificado:
```
- Filtra corretamente os produtos de uma página para exibir somente os daquela categoria
```
=> [GRUPO 12] Requisito 6 - Selecione uma categoria e mostre somente os produtos daquela categoria

src/components/InputSearch/InputSearch.js, src/components/InputSearch/categories.js, src/components/InputSearch/categories.jsx
Cria as LI's com o nome de cada categoria, a funcao esta quase finalizada, porem nao consegui renderizar na tela
=> [Requisito 04] Nao finalizado

src/App.js, src/Components/Home.jsx, src/Components/ShoppingCart.jsx
=> Main group 9 requisito3

src/components/CategoriesFilter.js, src/pages/Home.js
*Abaixo, escreva o checklist para esta tarefa*
---
- A função que faz a requisição já está pronta;
- Você só precisa alterar a renderização para exibir uma lista de radio buttons, por ordem alfabética;
=> [ Requisitos 4 e 6][ Grupo 1 ] Categories filter optimise

src/pages/Home.js
=> [ Requisitos 1 e 6 ] [ Grupo 1 ] Conditional render home elements

src/components/ProductCard.js, src/pages/Home.js
- ProductCard deverá renderizar:
=> [ Requisito 5, 7 e 8 ] [ Grupo 1 ] Product card component

src/App.js, src/components/Card.js, src/components/ProductDetail.js
PRIORIDADE 3 - Como pessoa usuária, eu quero clicar no card do produto e visualizar a exibição detalhada do produto com nome do produto, imagem, preço e especificação técnica. A tela também deve possuir um botão que leve ao carrinho de compras.
-   [Tela - Detalhamento do produto](https://github.com/tryber/sd-013-a-project-frontend-online-store/tree/master/wireframes/card_07.png)
**Observações técnicas**
A exibição detalhada de um produto será a página para exibir tudo o que se tem acerca de um produto específico.
-   Adicione o atributo  `data-testid`  com o valor  `product-detail-link`  no elemento que ao ser clicado, enviará a pessoa que usa a aplicação para a página de detalhes do produto. Você deve adicionar esse atributo para todos os produtos.
-   Adicione o atributo  `data-testid` …
=> [GRUPO 12] Requisito 7 - Redirecione para uma tela com a exibição detalhada ao clicar na exibição resumida de um produto

src/pages/CarShop.jsx, src/pages/Home.jsx, src/pages/ProductCard.jsx, src/pages/ProductList.jsx
O cart está bem simples ainda. Outros requisitos vão pedir que ele seja atualizado.
=> [Grupo 4] Requisito 8

src/components/HomeMessage.js, src/components/ListProduct.js, src/components/Product.js
=> [ Rafael Janovicci ] group 8 req 5

package-lock.json, package.json, src/App.js, src/components/AddProduct.jsx, src/components/CartItem.jsx, src/components/CategoriesList.jsx, src/components/Header.jsx, src/components/Search.jsx, src/components/ShoppingCartButton.jsx, src/pages/Home.jsx, src/pages/Home.module.css, src/pages/ProductDetails.jsx, src/pages/Products.jsx, src/pages/ShopCart.jsx, src/services/api.js, src/services/localStorage.js
Requisitos Obrigatórios
Requisitos Bônus
=> [Grupo 19] Frontend Online Store - Workflow

src/components/ProductCard.js, src/components/componentsIndex.js, src/pages/Home.js, src/pages/ProductDetails.js
=> [ Grupo 1 ] Chamar o componente <AddToCart /> nos componentes <ProductDetails /> e <ProductCard />

src/components/Card.js, src/components/CardsList.js, src/pages/Home.js, src/pages/ShoppingCart.js
Na tela de listagem de produtos, permitir adicionar o produto ao carrinho.
Observações técnicas
Configure uma forma de adicionar produtos ao carrinho de compras a partir da tela de listagem de produtos.
Adicione o atributo data-testid com o valor product-add-to-cart nos elementos que executam a ação de adicionar os produtos ao carrinho de compras.
Desenvolva algo da forma simples: um elemento adiciona um produto.
Adicione o atributo data-testid com o valor shopping-cart-product-name no elemento que possui o nome do produto na tela do carrinho de compras. Você deve adicionar esse atributo para todos os produtos.
Adicione o atributo data-testid com o valor shopping-cart-product-quantity no elemento que possui a quantidade do produto na tela do carrinho de compras. Você deve adicionar esse …
=> [Grupo 12] - 8. Adicione produtos a partir da tela de listagem de produtos

src/App.js, src/pages/PageDetails.jsx
=> Grupo 10 - Requisito 9

src/App.css, src/components/CategoriesList.js, src/pages/Home.js, src/pages/ProductCard.js, src/services/api.js
=> [Grupo 14] Requisito 6 (e refatorada API)

src/components/CartPage.js, src/components/ProductDetail.js, src/components/Products.js
Refatorei a parte do array carrinho, criei um objeto com duas chaves, refatorei algumas coisas pontuais no Products para o teste 3 voltar a passar. O requisito 9 está com um bug no test, embora aparentemente esteja pronto.
=> requisito9 com bug no test

src/App.js, src/components/Produtos.js, src/pages/Home.js, src/pages/ProdutoDetalhado.js
=> [Grupo 2] Requisito 7

src/components/FormCommentary.js, src/pages/ProductDetails.js
=> [Grupo 30] - Requisito 11

src/components/Category.js, src/components/MainPage.css, src/components/MainPage.js, src/components/ProductDetail.js, src/components/Products.js
fiz a estilização da página principal e também alguns ajustes semânticos no html.
=> estilizaçao da pag principal

src/Components/PageDetails.jsx, src/Components/ProductCard.jsx, src/Components/ShoppingCart.jsx
=> Main group 9 requisito9

src/components/FormEvaluation.js, src/components/MainPage.css, src/components/MainPage.js, src/components/ProductDetail.js, src/components/ReviewList.js
=> Requisito11

src/Componentes/Carrinho.css
=> mudando a cor de fundo
